server:
  port: 9001


write:
    url:
      ignoreUrlList:
        - /demo/client
        - /url/demo/client
        - /url/demo/server
      x_application_idIgnoreUrlList:
        - /demo/client
        - /demo/client
        - /demo/client
      authorizationIgnoreUrlList:
        - /demo/client
        - /demo/client
        - /demo/client
      specialTokenList:
        - /demo/client
        - /demo/client
        - /demo/client


spring:
  profiles:
    active: dev
  cloud:
    gateway:
      # 全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
      # 路由规则配置
      routes:
        - id: demo-client # 规则ID
          uri: lb://demo-client # lb表示启用loadbalancer负载均衡器
          predicates:
            - Path=/demo/client/** # 页面请求gateway的ip+端口/api-order就会进入这个断言规则里面，然后转发到上面的order-service服务
          filters:
            - StripPrefix=1 # 这里是去掉上面路径中的/api-order这一层，完整的转发路径是127.0.0.1:8000/api-order/add/order

        - id: demo-server
          uri: lb://demo-server
          predicates:
            - Path=/demo/server/**
          filters:
            - StripPrefix=1
